name: Next.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 112.72.119.81 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        rsync -avz --delete .next node_modules package.json package-lock.json ${{ secrets.SSH_USERNAME }}@112.72.119.81:/web3/ant-design-web3-demo
        ssh ${{ secrets.SSH_USERNAME }}@112.72.119.81 "cd /web3/ant-design-web3-demo && pm2 restart web3-demo || pm2 start npm --name web3-demo -- start"